### ISSUE TITLE
choosing plain decorator results in error 400

### ISSUE THREAD

**Issue by LeSpocky** [penguineer/cleanURI-legacy#1]
input: [die URL hier](https://secure.reichelt.de/RING-POCKET-LI/3/index.html?;ACTION=3;LA=5;ARTICLE=118936;artnr=RING+POCKET+LI;SID=12Ts0RUX8AAAIAAHtEzpQd781216be360f2863023143051c8d8f1)

radio button "plain" gewählt, fehler:

```
HTTP Status 400 - Invalid decorator label!
type Status report
message Invalid decorator label!
description The request sent by the client was syntactically incorrect (Invalid decorator label!).
```

**Comment by penguineer** [comment]
Fixed in https://github.com/penguineer/cleanURI/commit/8d5abdb8dedf83a3c740961b90b906cdf60f0806
